#!/usr/bin/env bash

usage() {
    printf "Usage:\n"
    printf "\t%s [options]\n" $0
    printf "Options:\n"
    printf "\t-h\tdisplays this message\n"
    printf "\t-r\tfetch from remote repo\n"
    printf "\t-b\tfull build (YouCompleteMe)\n"
    printf "\t-d\tchange destination (default is \$HOME)\n"
    printf "\t-l\tlight configuration (for command-line-only environments)\n"
}

fetch_remote() {
    git pull origin master
    git submodule update --init --recursive
}

build() {
    python3 ~/.vim/pack/plugins/start/YouCompleteMe/install.py \
        --clangd-completer \
        --ts-completer \
        --rust-completer \
        --java-completer
}

RSYNC="rsync -a --copy-links"

OPTERR=0
REMOTE=false
BUILD=false
SRC="$(dirname "$BASH_SOURCE")"
DEST="$HOME"
LIGHT=false

while getopts "rbd:lh" o; do
    case "$o" in
        r)
            REMOTE=true
            ;;
        b)
            BUILD=true
            ;;
        d)
            DEST=$OPTARG
            ;;
        l)
            LIGHT=true
            ;;
        h|*)
            usage
            [ h == "$o" ]
            exit $?
            ;;
    esac
done

$REMOTE && fetch_remote
$BUILD && build

$RSYNC "$SRC/common/" "$DEST"

$LIGHT || $RSYNC "$SRC/main/" "$DEST"

exit 0
