#!/usr/bin/env bash

usage() {
    printf "Usage:\n"
    printf "\t%s [options]\n" "$0"
    printf "Options:\n"
    printf "\t-h\tdisplays this message\n"
    printf "\t-r\tfetch from remote repo\n"
    printf "\t-d\tchange destination (default is \$HOME)\n"
    printf "\t-l\tlightweight configuration (for command-line-only environments)\n"
}

fetch_remote() {
    git pull origin HEAD
    git submodule update --init --recursive
}

RSYNC="rsync -a --copy-links"

OPTERR=0
REMOTE=false
SRC="$(dirname "${BASH_SOURCE[0]}")"
DEST="$HOME"
LIGHTWEIGHT=false

while getopts "rbd:lh" o; do
    case "$o" in
        r)
            REMOTE=true
            ;;
        d)
            DEST=$OPTARG
            ;;
        l)
            LIGHTWEIGHT=true
            ;;
        h|*)
            usage
            [ h == "$o" ]
            exit $?
            ;;
    esac
done

CURRENT_DIR=$(pwd)
cd "$SRC" || exit 1

$REMOTE && fetch_remote

$RSYNC "./common/" "$DEST"

if ! $LIGHTWEIGHT; then
    $RSYNC "./main/" "$DEST"
fi

cd "$CURRENT_DIR" || exit 1

exit 0
