#!/usr/bin/env bash

. ~/bin/lib/keyboard.sh
keyboard_configuration

. ~/bin/lib/monitors.sh
bspc monitor $(primary_monitor) -d 1 2 3 4 5 6 7 8 9 0
monitor_configuration

# for overlapping borders
BW=3
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left; do
	bspc config ${side}_padding $BW
done

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# for some reason the configuration options above mess with the order of the monitors
bspc wm -O "$(primary_monitor)" "$(secondary_monitor)"

bspc config normal_border_color "#a89984"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"

bspc rule -a Firefox desktop='2'
bspc rule -a Zathura state=tiled

bspc config external_rules_command "/home/fransic/.config/bspwm/external_rules"

picom &

wmname LG3D

feh --bg-fill ~/Pictures/bg.png &

sxhkd &

~/bin/auto_configure_monitors &

~/bin/panel/panel &
