#!/usr/bin/env bash

#monitor_configuration
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
"$HOME/bin/auto_configure_monitors" --init

# for overlapping borders
BW=3
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left; do
	bspc config ${side}_padding $BW
done

bspc config split_ratio 0.50
bspc config automatic_scheme alternate
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#a89984"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"
bspc config presel_feedback_color "#fabd2f"

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen all

bspc rule -a Alacritty:main desktop='1'
bspc rule -a Zathura state=tiled
bspc rule -a feh state=floating center=true

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

picom &

wmname LG3D

"$HOME/bin/auto_configure_monitors" &

feh --bg-fill "$HOME/Pictures/bg.png" &

sxhkd &

alacritty --class main --command "$HOME/bin/main" &

